const ProfileActionType = {
	TOGGLE_USERINFORMATION_HIDDEN: 'TOGGLE_USERINFORMATION_HIDDEN',
	TOGGLE_BUYINGHISTORY_HIDDEN: 'TOGGLE_BUYINGHISTORY_HIDDEN',
	TOGGLE_RATINGS_HIDDEN: 'TOGGLE_RATINGS_HIDDEN',
	SET_BUYINGHISTORY_DATA: 'SET_BUYINGHISTORY_DATA'
}

export default ProfileActionType;